// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2_2MqXmejYtEQ8q80WvlV58Bq9TQRZwM',
    appId: '1:274217185269:web:594bfbece4e2e2cb273abc',
    messagingSenderId: '274217185269',
    projectId: 'farming-d871f',
    authDomain: 'farming-d871f.firebaseapp.com',
    storageBucket: 'farming-d871f.firebasestorage.app',
    measurementId: 'G-7GVKGC3HRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcyfaIDXC_DLksh4CYf3_gbDOZTU8pbv8',
    appId: '1:274217185269:android:cba030209220c79f273abc',
    messagingSenderId: '274217185269',
    projectId: 'farming-d871f',
    storageBucket: 'farming-d871f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdT1exd0KRQsXI1kBpNW_GZPuB4XBd_UU',
    appId: '1:274217185269:ios:24b8f1df7c19dc9d273abc',
    messagingSenderId: '274217185269',
    projectId: 'farming-d871f',
    storageBucket: 'farming-d871f.firebasestorage.app',
    iosBundleId: 'com.example.farming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdT1exd0KRQsXI1kBpNW_GZPuB4XBd_UU',
    appId: '1:274217185269:ios:24b8f1df7c19dc9d273abc',
    messagingSenderId: '274217185269',
    projectId: 'farming-d871f',
    storageBucket: 'farming-d871f.firebasestorage.app',
    iosBundleId: 'com.example.farming',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2_2MqXmejYtEQ8q80WvlV58Bq9TQRZwM',
    appId: '1:274217185269:web:ff2bb458f0c61c88273abc',
    messagingSenderId: '274217185269',
    projectId: 'farming-d871f',
    authDomain: 'farming-d871f.firebaseapp.com',
    storageBucket: 'farming-d871f.firebasestorage.app',
    measurementId: 'G-SZ9XG7MHXT',
  );
}
